# Generated by Django 5.2.8 on 2025-11-16 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget_helper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
    ]
