# Generated by Django 5.2.8 on 2025-11-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_helper', '0002_remove_category_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
